### ISSUE TITLE
500 error at user/lastEntry endpoint

### ISSUE THREAD

**Issue by coxm** [alakajam-team/alakajam#106]
Visit e.g. https://alakajam.com/api/user/administrator/latestEntry?pretty=true (I was directed here after clicking a link on the API page).

**Comment by mkalam-alami** [comment]
Stacktrace:

```
TypeError: Cannot read property 'get' of undefined
    at _getAttributes (/var/www/alakajam/controllers/api-controller.js:180:30)
    at userLatestEntry (/var/www/alakajam/controllers/api-controller.js:160:25)
    at <anonymous>
```
