### ISSUE TITLE
JS doesn't build if "npm install" is run wih "--production" flag

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#204]
```
^[[31m03:43:33.252 ERROR (/core/middleware.js:310)^[[39m Something went wrong, sorry about that.
Error: Cannot find module 'regenerator-runtime/runtime' from '/var/www/alakajam/client'
    at /var/www/alakajam/node_modules/browserify-middleware/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/var/www/alakajam/node_modules/browserify-middleware/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/var/www/alakajam/node_modules/browserify-middleware/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/var/www/alakajam/node_modules/browserify-middleware/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/var/www/alakajam/node_modules/browserify-middleware/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /var/www/alakajam/node_modules/browserify-middleware/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
```

**Comment by ttencate** [comment]
I can't reproduce this. I did:

```
rm -rf node_modules/
npm install --production
node server.js  # no errors
NODE_ENV=production node server.js  # no errors
```

Going to assume that this got accidentally fixed.
