### ISSUE TITLE
Tag-related crash during game submission

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#239]
No idea what the exact scenario is.

Theory: double-click on save triggers attempt at double-adding the same tag to an entry.

```
03:35:15.135 ERROR (/core/middleware.js:317) Something went wrong, sorry about that.
error: duplicate key value violates unique constraint "entry_tag_entry_id_tag_id_unique"
    at Connection.parseE (/var/www/alakajam/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/var/www/alakajam/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/var/www/alakajam/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
```

**Comment by mkalam-alami** [comment]
Similar stacktrace reproduced in 2023

```
0|alakajam | 2023-02-26 20:14:09.418 ERROR (/server/error.middleware.ts:60) HTTP 500: Something went wrong, sorry about that.
0|alakajam | error: insert or update on table "entry_tag" violates foreign key constraint "entry_tag_tag_id_foreign"
0|alakajam |     at Parser.parseErrorMessage (/var/www/alakajam/node_modules/pg-protocol/src/parser.ts:357:11)
0|alakajam |     at Parser.handlePacket (/var/www/alakajam/node_modules/pg-protocol/src/parser.ts:186:21)
0|alakajam |     at Parser.parse (/var/www/alakajam/node_modules/pg-protocol/src/parser.ts:101:30)
0|alakajam |     at Socket.<anonymous> (/var/www/alakajam/node_modules/pg-protocol/src/index.ts:7:48)
0|alakajam |     at Socket.emit (events.js:315:20)
0|alakajam |     at addChunk (internal/streams/readable.js:309:12)
0|alakajam |     at readableAddChunk (internal/streams/readable.js:284:9)
0|alakajam |     at Socket.Readable.push (internal/streams/readable.js:223:10)
0|alakajam |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```
