### ISSUE TITLE
[SQLite] Deleting an entry makes the server hang forever

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#265]
1. Launch dev server with clean database.
2. Log in as `administrator`.
3. Head to http://localhost:8000/2nd-alakajam/2/super-game/edit.
4. Click `Delete`.

For me, the server just stops responding. Eventually I get this in the console:

```
10:55:20.655 ERROR (/core/middleware.js:310) Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Timeout._onTimeout (/home/thomas/alakajam/node_modules/knex/lib/client.js:287:18)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
From previous event:
    at Client_SQLite3.acquireConnection (/home/thomas/alakajam/node_modules/knex/lib/client.js:280:12)
    at /home/thomas/alakajam/node_modules/knex/lib/runner.js:208:30
From previous event:
    at /home/thomas/alakajam/node_modules/knex/lib/runner.js:206:35
From previous event:
    at Runner.ensureConnection (/home/thomas/alakajam/node_modules/knex/lib/runner.js:205:34)
    at Runner.run (/home/thomas/alakajam/node_modules/knex/lib/runner.js:51:42)
    at Builder.Target.then (/home/thomas/alakajam/node_modules/knex/lib/interface.js:35:43)
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)
```

**Comment by ttencate** [comment]
Also happening when saving an entry, after adding a team mate. Not yet sure if it's 100% reproducible. Possibly only occurs on SQLite?

**Comment by mkalam-alami** [comment]
It's indeed related to SQLite allowing a single transaction per connection.

Code that specifically tries to run reads & writes in the same explicit transaction (`db.transaction(...)`) can easily get stuck in SQLite.

**Comment by ttencate** [comment]
The stack trace of the second one (adding teammates to an entry) is slightly more informative:

```
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Timeout._onTimeout (/home/thomas/alakajam/node_modules/knex/lib/client.js:287:18)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
From previous event:
    at Client_SQLite3.acquireConnection (/home/thomas/alakajam/node_modules/knex/lib/client.js:280:12)
    at /home/thomas/alakajam/node_modules/knex/lib/runner.js:208:30
From previous event:
    at /home/thomas/alakajam/node_modules/knex/lib/runner.js:206:35
From previous event:
    at Runner.ensureConnection (/home/thomas/alakajam/node_modules/knex/lib/runner.js:205:34)
    at Runner.run (/home/thomas/alakajam/node_modules/knex/lib/runner.js:51:42)
    at Builder.Target.then (/home/thomas/alakajam/node_modules/knex/lib/interface.js:35:43)
    at Child.<anonymous> (/home/thomas/alakajam/node_modules/bookshelf/lib/model.js:1046:36)
From previous event:
    at Child.<anonymous> (/home/thomas/alakajam/node_modules/bookshelf/lib/model.js:1045:125)
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)
From previous event:
    at Child.<anonymous> (/home/thomas/alakajam/node_modules/bookshelf/lib/model.js:970:8)
From previous event:
    at /home/thomas/alakajam/services/event-service.js:363:22
    at <anonymous>
```

**Comment by ttencate** [comment]
Found another one: accepting invites.
