### ISSUE TITLE
JS build possibly does nothing when server is launched from outside the sources

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#405]
Running `pm2 restart alakajam` in production did not rebuild the JS file, it might be related from the server being launched from a different folder than the sources root.

**Comment by Thrainsa** [comment]
Maybe it's linked, I've got this message after upgrading the website when I restart the server:

0|alakajam  | 2019-03-11 07:54:26.765 ERROR (/data/www/alakajam/server.js:242) Hash: c1617568de5175307620
0|alakajam  | Version: webpack 4.29.3
0|alakajam  | Time: 718ms
0|alakajam  | Built at: 2019-03-11 19:54:26
0|alakajam  |       Asset      Size  Chunks  Chunk Names
0|alakajam  |     site.js  3.14 KiB       0  site
0|alakajam  | site.js.map  4.43 KiB       0  site
0|alakajam  | Entrypoint site = site.js site.js.map
0|alakajam  | ERROR in ./assets/js/site.js
0|alakajam  | Module build failed (from ./node_modules/babel-loader/lib/index.js):
0|alakajam  | Error: Cannot find module '@babel/preset-env' from '/home/alakajam'
0|alakajam  |     at Function.module.exports [as sync] (/data/www/alakajam/node_modules/resolve/lib/sync.js:40:15)
0|alakajam  |     at resolveStandardizedName (/data/www/alakajam/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
0|alakajam  |     at resolvePreset (/data/www/alakajam/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
0|alakajam  |     at loadPreset (/data/www/alakajam/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
0|alakajam  |     at createDescriptor (/data/www/alakajam/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
0|alakajam  |     at items.map (/data/www/alakajam/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
0|alakajam  |     at Array.map (<anonymous>)
0|alakajam  |     at createDescriptors (/data/www/alakajam/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
0|alakajam  |     at createPresetDescriptors (/data/www/alakajam/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
0|alakajam  |     at passPerPreset (/data/www/alakajam/node_modules/@babel/core/lib/config/config-descriptors.js:58:96)
0|alakajam  |     at cachedFunction (/data/www/alakajam/node_modules/@babel/core/lib/config/caching.js:33:19)
0|alakajam  |     at presets.presets (/data/www/alakajam/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
0|alakajam  |     at mergeChainOpts (/data/www/alakajam/node_modules/@babel/core/lib/config/config-chain.js:320:26)
0|alakajam  |     at /data/www/alakajam/node_modules/@babel/core/lib/config/config-chain.js:283:7
0|alakajam  |     at buildRootChain (/data/www/alakajam/node_modules/@babel/core/lib/config/config-chain.js:68:29)
0|alakajam  |     at loadPrivatePartialConfig (/data/www/alakajam/node_modules/@babel/core/lib/config/partial.js:85:55)
0|alakajam  |     at Object.loadPartialConfig (/data/www/alakajam/node_modules/@babel/core/lib/config/partial.js:110:18)
0|alakajam  |     at Object.<anonymous> (/data/www/alakajam/node_modules/babel-loader/lib/index.js:140:26)
0|alakajam  |     at Generator.next (<anonymous>)
0|alakajam  |     at asyncGeneratorStep (/data/www/alakajam/node_modules/babel-loader/lib/index.js:3:103)
0|alakajam  |     at _next (/data/www/alakajam/node_modules/babel-loader/lib/index.js:5:194)
0|alakajam  |     at /data/www/alakajam/node_modules/babel-loader/lib/index.js:5:364
