### ISSUE TITLE
Tournament-related front page 500 error

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#513]
People not being already present in the high scores at the start of the event may actually have never been able to reach the front page.... ?

```
0|alakajam | 2020-04-06 13:35:55.960 ERROR (/server/core/log.ts:43) HTTP 500: Something went wrong, sorry about that.
0|alakajam | Template render error: (/data/www/alakajam/server/home/home.html) [Line 34, Column 35]
0|alakajam |   Error: Unable to call `tournamentScore["get"]`, which is undefined or falsey
0|alakajam |     at Object._prettifyError (/data/www/alakajam/node_modules/nunjucks/src/lib.js:36:11)
0|alakajam |     at /data/www/alakajam/node_modules/nunjucks/src/environment.js:567:19
0|alakajam |     at eval (eval at _compile (/data/www/alakajam/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:271:12)
0|alakajam |     at b_body (eval at _compile (/data/www/alakajam/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:264:3)
0|alakajam |     at eval (eval at _compile (/data/www/alakajam/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:270:83)
0|alakajam |     at b_styles (eval at _compile (/data/www/alakajam/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:345:1)
0|alakajam |     at eval (eval at _compile (/data/www/alakajam/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:160:85)
0|alakajam |     at /data/www/alakajam/node_modules/nunjucks/src/environment.js:619:9
0|alakajam |     at eval (eval at _compile (/data/www/alakajam/node_modules/nunjucks/src/environment.js:637:18), <anonym
```

**Comment by mkalam-alami** [comment]
This is a caching issue that could cause 500 errors esp during high traffic times ; annoying but didn't not happen that often during the tournament.
