### ISSUE TITLE
Entry tags

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#81]
Would work just like platforms, except we'll let people fill what they want:

* Techs (Unity, Pico8....)
* Game genres (RPG, Arcarde...)
* Art styles (Pixel Art...)
* ...

**Comment by mkalam-alami** [comment]
I'm trying the `tags` branch, the front page gives me a 500 error:

```
select count(distinct "id") from (select * from "entry" where "event_id" = $1) - la sous-requête du FROM doit avoir un alias
Stack trace
    ...
    at Builder.Target.then (D:\Users\u02e109\Documents\Scripts\alakajam\node_modules\knex\lib\interface.js:35:43)
    at count (D:\Users\u02e109\Documents\Scripts\alakajam\plugins\bookshelf-pagination.js:188:10)
    at Child.fetchPage (D:\Users\u02e109\Documents\Scripts\alakajam\plugins\bookshelf-pagination.js:202:48)
    at Object.findGames (D:\Users\u02e109\Documents\Scripts\alakajam\services\event-service.js:641:16)
    at index (D:\Users\u02e109\Documents\Scripts\alakajam\controllers\main-controller.js:113:43)
```

**Comment by mkalam-alami** [comment]
Using a fresh Sqlite DB I don't have the error anymore, will test it again tonight.
